### ISSUE TITLE
Add credits to the credits page

### ISSUE THREAD

**Issue by EddieEldridge** [EddieEldridge/sounds-of-middle-earth#11]
We should credit any people who created things we are using on the site

- We should include links to each artists page
- We should credit the makers of the videos
- We should credit the maker of the map

**Comment by syafiqnazim** [comment]
Hi @EddieEldridge can I take this issue?

**Comment by EddieEldridge** [comment]
> Hi @EddieEldridge can I take this issue?

Hey @syafiqnazim, that sounds good. Go for it.

**Comment by yashbajoria05** [comment]
please assign this issue to me
