### ISSUE TITLE
Create a header/logo

### ISSUE THREAD

**Issue by EddieEldridge** [EddieEldridge/sounds-of-middle-earth#8]
It would be nice to create a basic header/logo for the site that we can display on the Readme and in the top left of the expandable window. 

- It should be transparent 
- It should consist of the words 'Sounds of Middle-earth'

**Comment by melaniedrevet** [comment]
Hello, I can take care of It ! 

If I understood correctly, you want a logo for your site? Do you have any special requests ?

**Comment by EddieEldridge** [comment]
Hey @melaniedrevet ! Indeed yes, I would love to have a logo for the site for both 'branding' and to display possibly in these 2 locations.

![Screenshot 2022-02-03 at 12 55 20](https://user-images.githubusercontent.com/22448079/152347214-b64db6aa-62d2-401f-99fc-df71337c877f.png)

![Screenshot 2022-02-03 at 12 55 56](https://user-images.githubusercontent.com/22448079/152347191-3f79545e-a829-4334-8eb3-5c7acccda26d.png)
ations.

In terms of special requests, it would be nice if it would fit in with the existing colours and themes (e.g not bright pink or green). Feel free to take some try out some things and see what you like.

Some fonts that might be useful are 

- https://www.dafont.com/ringbearer.font
- https://www.dafont.com/aniron.font

but feel free to use whatever you like!

Feel free to use whatever materials/finish you like also such as wood, metal or plain.

The logo can simply be an icon with no text, the text 'Sounds of Middle-earth/Sounds of Middle-Earth' or a combination of both. 

Any other questions, feel free to get in touch on Discord (Medik#0001) or via my email (eddie.eldridge@hotmail.com).

Thanks!

**Comment by melaniedrevet** [comment]
Hello @EddieEldridge   !

I'm coming back to you to show you what I've done. 
**Please let me know what you think and if you see any changes.**

--------

I used the colors of the site, and the font "29LT Riwaya", which is very similar to "Ringbearer".

1. **First, I made a logo with the text, which could be put on top of the card. Here are the variations of the logo.**

<img width="542" alt="LogoNom" src="https://user-images.githubusercontent.com/76695871/153007655-461ef69b-9343-4e60-b031-6f11837a8d7a.png">

- And here it is in visual on the site  


<img width="370" alt="Logo1-Nom" src="https://user-images.githubusercontent.com/76695871/153008031-d88cb549-0ae6-477e-80de-e225a3f704d4.png">      <img width="370" alt="Logo2-Nom" src="https://user-images.githubusercontent.com/76695871/153008125-189d7358-c0b9-4ecc-ac48-466049330dc1.png"><img width="370" alt="Logo3-Nom" src="https://user-images.githubusercontent.com/76695871/153008156-8823b1e4-0ce5-4751-b593-4116d0932822.png">

--------

**2. Then I made 3 types of more visual logos to go above the menu**

- This one, which represents a compass with a musical note inside and the first letters of "Sounds Of Middle Earth".

<img width="200" alt="Vue-Logo2" src="https://user-images.githubusercontent.com/76695871/153009391-5e356d8c-edff-442d-99b5-03394a84191f.png">  <img width="200" alt="Logo2" src="https://user-images.githubusercontent.com/76695871/153008803-fa2934e3-b231-491b-9b63-5c20365f3f50.png">  


- These variants, which also represent a compass, but this time with a black background and 2 types of musical notes.

<img width="570" alt="Vues-4Logos" src="https://user-images.githubusercontent.com/76695871/153009573-11b58e5e-fbd7-4408-ba1e-acc2cc7e6801.png">  <img width="200" alt="4Logos" src="https://user-images.githubusercontent.com/76695871/153009339-77d63428-2957-4528-91cb-0ea7b3db87b1.png">  

- Finally, the one I personally prefer, which represents a map with a musical note on one side and a compass on the other.

<img width="148" alt="Vue-Logo1" src="https://user-images.githubusercontent.com/76695871/153009871-bf608286-8dd4-4d55-b1f1-2f314aa4afa5.png">  <img width="210" alt="Logo1" src="https://user-images.githubusercontent.com/76695871/153009958-cf4e1fe6-343d-4123-9cbe-1f1eae0d7a1f.png">

--------

**Comment by melaniedrevet** [comment]
Hi @EddieEldridge, glad you like the logos and that their meanings are understandable !

I agree with you, the logos with the text are a bit hard to read, I had a hard time putting together my design idea.

So I opened a Pull Request with the requested changes.
